### ISSUE TITLE
Nächster Schrit nach dem "result"

### ISSUE THREAD

**Issue by ProfessorZweistein** [LadyBlue19/BdK6.5.3_P3_SoSe21_Jana_Bode#1]
Hallo Jana,

ich glaube, als nächstes müsstest du innerhalb des "results" die ID und innerhalb dessen dann wiederum den Titel und das Datum "ansteuern". Probiers mal mit print(result["27708327"][title].

**Comment by LadyBlue19** [comment]
Vielen Dank :D
Leider hat das mit dem print(result["27708327"][title]) nicht funktioniert. Da aber jemand anderes das gleiche Problem hatte und nicht weiter gekommen ist, hat er Förstner hier weiter geholfen, so dass ich jetzt nur noch die anderen IDs machen muss.
